# Generated by Django 4.2.11 on 2026-07-23 07:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='Silk', max_length=64)),
                ('legal_name', models.CharField(blank=True, default='', max_length=128)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('browser_title', models.CharField(blank=True, default='Silk — AI Dealmaking Workspace', max_length=128)),
                ('logo_url', models.CharField(blank=True, default='', help_text='Full-colour logo (SVG preferred). Used in app chrome.', max_length=512)),
                ('logo_mono_url', models.CharField(blank=True, default='', max_length=512)),
                ('favicon_url', models.CharField(blank=True, default='', max_length=512)),
                ('export_logo_url', models.CharField(blank=True, default='', help_text='Logo embedded in generated PDF/DOCX/PPTX/XLSX.', max_length=512)),
                ('export_footer_text', models.CharField(blank=True, default='', help_text='Footer line on every generated document.', max_length=255)),
                ('support_email', models.CharField(blank=True, default='', max_length=255)),
                ('primary_color', models.CharField(blank=True, default='#1F6F4A', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branding',
                'verbose_name_plural': 'Branding',
                'db_table': 'brand_config',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iso2', models.CharField(db_index=True, max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, default='', max_length=3)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('dial_code', models.CharField(blank=True, default='', max_length=8)),
                ('home_currency', models.CharField(blank=True, default='', help_text='Default reporting currency for companies headquartered here.', max_length=3)),
                ('sort_order', models.IntegerField(default=100, help_text='Lower sorts first — pin common countries.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'country_master',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FundraiseBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_no', models.IntegerField(help_text='1–7, ascending.', unique=True)),
                ('label', models.CharField(help_text='e.g. "$1M"', max_length=32)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('typical_stage', models.CharField(blank=True, default='', max_length=64)),
                ('investor_types', models.JSONField(blank=True, default=list, help_text='Who funds this size, e.g. ["Angels","MicroVC","VC"]. From the Outline §3.4.')),
                ('typical_dilution_low_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('typical_dilution_high_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fund-raise Bucket',
                'db_table': 'fundraise_bucket',
                'ordering': ('bucket_no',),
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_ccy', models.CharField(default='USD', max_length=3)),
                ('quote_ccy', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Units of quote per 1 unit of base. USD→INR ≈ 84.', max_digits=20)),
                ('as_of_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, default='manual', help_text="Provider or 'manual'. Recorded on every artefact.", max_length=128)),
            ],
            options={
                'db_table': 'fx_rate',
                'ordering': ('-as_of_date',),
            },
        ),
        migrations.CreateModel(
            name='ProfileSectionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('structured', 'Structured fields'), ('narrative', 'AI narrative'), ('list', 'List of records'), ('documents', 'Document group'), ('indicator', 'Computed indicator')], default='narrative', max_length=16)),
                ('sort_order', models.IntegerField(default=100)),
                ('llm_role', models.CharField(blank=True, default='', help_text='Role used when regenerating this section.', max_length=48)),
                ('required_for_creation', models.BooleanField(default=False, help_text='Must be present before a profile can be generated.')),
                ('required_for_completeness', models.BooleanField(default=False, help_text="Counts toward the 'complete' state that unlocks resume-to-last-stage routing (C2).")),
                ('is_editable', models.BooleanField(default=True)),
                ('is_regenerable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Profile Section',
                'db_table': 'profile_section_config',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, help_text="LLM role key, e.g. 'readiness_summary'. Must match the role used in code.", max_length=48)),
                ('system_prompt', models.TextField(help_text='System message. Describes behaviour, tone and the exact JSON shape the model must return. Numbers must never be requested from the model — they are injected as context.')),
                ('user_prompt', models.TextField(blank=True, default='', help_text='User message. Usually a short instruction; the real payload travels in the context block.')),
                ('context_keys', models.JSONField(blank=True, default=list, help_text='Reference only — context keys this role receives.')),
                ('notes', models.TextField(blank=True, default='', help_text='Why this prompt is worded the way it is. For the next admin.')),
                ('version_no', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt',
                'verbose_name_plural': 'AI Prompts',
                'db_table': 'prompt_template',
            },
        ),
        migrations.CreateModel(
            name='StageDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_no', models.IntegerField(unique=True)),
                ('stage_key', models.CharField(max_length=48, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('purpose', models.TextField(blank=True, default='', help_text='Shown at the top of the stage page (PRD §2.3).')),
                ('overview', models.TextField(blank=True, default='')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='[{"key","label","explanation"}] — advisory only (C6).')),
                ('next_actions', models.JSONField(blank=True, default=list)),
                ('is_implemented', models.BooleanField(default=False, help_text="False renders a 'coming soon' state.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stage',
                'db_table': 'stage_definition',
                'ordering': ('stage_no',),
            },
        ),
        migrations.CreateModel(
            name='UiCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=96, unique=True)),
                ('text', models.TextField()),
                ('description', models.CharField(blank=True, default='', help_text='Where this appears in the product.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'UI Copy',
                'verbose_name_plural': 'UI Copy',
                'db_table': 'ui_copy',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='UpliftRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('condition_key', models.CharField(help_text="CKB flag that triggers this uplift, e.g. 'star_founder'.", max_length=64)),
                ('levels', models.IntegerField(default=2, help_text='Bucket levels to add when triggered.')),
                ('rationale', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'uplift_rule',
            },
        ),
        migrations.CreateModel(
            name='TractionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField(default=100, help_text='Lower evaluates first. First match wins.')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='e.g. {"arr_usd_min": 500000, "founder_full_time": true}')),
                ('rationale', models.TextField(blank=True, default='', help_text='Shown to the founder as the reason for the recommendation.')),
                ('advice_note', models.TextField(blank=True, default='', help_text="Extra guidance, e.g. the idea-stage 'come back in 3 months' advice from Outline §3.3(a).")),
                ('is_active', models.BooleanField(default=True)),
                ('recommended_bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traction_rules', to='platformcfg.fundraisebucket')),
            ],
            options={
                'db_table': 'traction_rule',
                'ordering': ('priority',),
            },
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('role',), name='uq_active_prompt_per_role'),
        ),
        migrations.AlterUniqueTogether(
            name='fxrate',
            unique_together={('base_ccy', 'quote_ccy', 'as_of_date')},
        ),
    ]
