# Generated by Django 4.2.11 on 2026-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformcfg', '0002_prompttemplate_tier_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='purpose',
            field=models.TextField(blank=True, default='', help_text="Plain-English explanation of what this prompt is for and when it runs. Shown to admins; seeded from the role's shipped notes."),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='tier',
            field=models.CharField(blank=True, choices=[('', 'Use shipped default'), ('simple', 'Simple — extract from supplied text (no tools)'), ('advanced', 'Advanced / Web — retrieve from the internet'), ('judgment', 'Judgement — reason over already-extracted data')], default='', help_text='Which KIND of work this prompt is. SIMPLE: the answer is in the supplied context — extraction, no tools, cheapest, highest volume. ADVANCED/WEB: the answer is NOT supplied and must be found on the internet — web search on, most expensive per call, bound it with max_uses. JUDGEMENT: reason over data another call already extracted — no tools, small input, so the strongest model is affordable here. Leave blank to use the shipped default for this role. The concrete model per tier is set per tenant under LLM → Tenant LLM tiers.', max_length=16),
        ),
    ]
