# Generated by Django 4.2.11 on 2026-08-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformcfg', '0003_judgment_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFlag',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'platform_flag',
                'ordering': ('key',),
            },
        ),
    ]
