# Generated by Django 5.1.15 on 2026-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platformcfg", "0007_lookup_models_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="added_from",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The company whose profile introduced this value.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="is_pending",
            field=models.BooleanField(
                default=False,
                help_text="Arrived with a company rather than being curated. An administrator confirms it, and for a sub-sector says which benchmark group it belongs to.",
            ),
        ),
        migrations.AddField(
            model_name="subsector",
            name="added_from",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The company whose profile introduced this value.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="subsector",
            name="is_pending",
            field=models.BooleanField(
                default=False,
                help_text="Arrived with a company rather than being curated. An administrator confirms it, and for a sub-sector says which benchmark group it belongs to.",
            ),
        ),
    ]
