# Generated by Django 4.2.11 on 2026-08-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('kind', models.CharField(choices=[('refresh', 'Data refresh'), ('extraction', 'Evidence extraction'), ('scoring', 'Assessment scoring'), ('rubric_review', 'AI rubric review'), ('matching', 'Investor matching'), ('import', 'Bulk import'), ('classification', 'Investor classification'), ('other', 'Other')], db_index=True, max_length=24)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('deal_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subject', models.CharField(blank=True, default='', help_text='Human-readable subject — company name, source name, query.', max_length=255)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('config_version', models.CharField(blank=True, default='', help_text='Config generation in force. Without it a historical result cannot be reproduced after a threshold changes.', max_length=64)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Completed'), ('warning', 'Completed with warnings'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diag_run_record',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('component', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('deal_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('source_location', models.CharField(blank=True, default='', help_text='file:line — traceable to origin without a debugger, the one genuinely useful habit from the original log format.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='diagnostics.runrecord')),
            ],
            options={
                'db_table': 'diag_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='runrecord',
            index=models.Index(fields=['kind', '-started_at'], name='diag_run_re_kind_02728d_idx'),
        ),
        migrations.AddIndex(
            model_name='runrecord',
            index=models.Index(fields=['deal_id', '-started_at'], name='diag_run_re_deal_id_864f53_idx'),
        ),
        migrations.AddIndex(
            model_name='runrecord',
            index=models.Index(fields=['correlation_id'], name='diag_run_re_correla_fb4ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='diagevent',
            index=models.Index(fields=['correlation_id', 'created_at'], name='diag_event_correla_c00b82_idx'),
        ),
    ]
