# Generated by Django 4.2.11 on 2026-08-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectordealdata',
            name='clubbed_group',
            field=models.CharField(blank=True, db_index=True, default='', help_text='For sub-sector rows: the group this raw label rolls up into. Scoring uses the group, not the raw label.', max_length=255),
        ),
        migrations.AddField(
            model_name='sectordealdata',
            name='investors_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sectordealdata',
            name='sample_quality',
            field=models.CharField(blank=True, default='', help_text='OK, or Thin when the deal count is too small for the percentile to mean anything.', max_length=32),
        ),
        migrations.AddField(
            model_name='sectordealdata',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sectordealdata',
            name='ticket_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sectordealdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sectordealdata',
            name='velocity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
