# Generated by Django 4.2.11 on 2026-08-11 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_sectordealdata_clubbed_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparameter',
            name='benchmark_level',
            field=models.CharField(blank=True, default='', help_text='sector | sub_sector — for percentile nodes, which population this reads from.', max_length=12),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='benchmark_metric',
            field=models.CharField(blank=True, default='', help_text='velocity | ticket | investors — which stored percentile column feeds this node.', max_length=16),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='companion_key',
            field=models.CharField(blank=True, default='', help_text='A second input this node is scored jointly with. E.1/F.1 take the WORSE of TAM size and TAM growth, because a large but stagnant market is not an attractive one.', max_length=48),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='definition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='if_missing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='is_workbook_input',
            field=models.BooleanField(default=True, help_text="True for the 80 rows of the workbook's Company Profile input sheet. False for nodes the workbook computes rather than collects — the deal-database percentiles — which must be excluded from the 'inputs captured (of 80)' count."),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='scoring_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='configparameter',
            name='where_to_find',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ConfigConstant',
            fields=[
                ('version', models.IntegerField(db_index=True, default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='NULL = platform default, used by every tenant. Set only to override the model for one tenant — rare, and it forks them off the platform scoring model.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'assess_config_constant',
                'indexes': [models.Index(fields=['tenant_id', 'key', '-version'], name='assess_conf_tenant__2fdc1a_idx')],
            },
        ),
    ]
