# Generated by Django 4.2.11 on 2026-07-06 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('doc_type', models.CharField(choices=[('upload', 'upload'), ('teaser', 'teaser'), ('deck', 'deck'), ('model', 'model'), ('im', 'im'), ('story', 'story')], max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('origin', models.CharField(choices=[('founder_uploaded', 'founder_uploaded'), ('fundos_generated', 'fundos_generated')], default='fundos_generated', max_length=24)),
                ('current_version_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('AI Draft Ready', 'AI Draft Ready'), ('In Review', 'In Review'), ('Founder Review', 'Founder Review'), ('Advisor Review', 'Advisor Review'), ('Approved', 'Approved'), ('Locked', 'Locked')], default='Not Started', max_length=24)),
                ('ai_review_status', models.CharField(blank=True, default='', max_length=24)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('perm', models.CharField(choices=[('view', 'view'), ('comment', 'comment'), ('suggest', 'suggest'), ('approve', 'approve'), ('edit', 'edit'), ('resolve', 'resolve')], max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='docs.document')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_permission',
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('shared', 'shared'), ('private', 'private')], default='shared', max_length=8)),
                ('anchor', models.JSONField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='docs.document')),
            ],
            options={
                'db_table': 'document_comment',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('version_no', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=12)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='docs.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('version_no', models.IntegerField(default=1)),
                ('storage_uri', models.CharField(blank=True, default='', max_length=512)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('ai_model_version', models.CharField(blank=True, default='', max_length=128)),
                ('source_prompt_ref', models.CharField(blank=True, default='', max_length=255)),
                ('scoring_config_version_id', models.UUIDField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, default='', max_length=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docs.document')),
            ],
            options={
                'db_table': 'document_version',
                'unique_together': {('document', 'version_no')},
            },
        ),
    ]
