# Generated by Django 4.2.11 on 2026-07-06 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyResearchSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('source_type', models.CharField(choices=[('website', 'website'), ('linkedin', 'linkedin'), ('market', 'market'), ('competitor', 'competitor'), ('industry', 'industry'), ('public_funding', 'public_funding'), ('patents', 'patents'), ('news', 'news'), ('awards', 'awards'), ('hiring', 'hiring')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=12)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_research_source',
                'indexes': [models.Index(fields=['deal_id', 'status'], name='company_res_deal_id_6fdb09_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='companyresearchsource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('deal_id', 'source_type'), name='uq_research_source_live'),
        ),
    ]
