# Generated by Django 4.2.11 on 2026-07-06 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Free-form feature block (Doc 6 §2 flags).')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password_env_var', models.CharField(blank=True, default='FUNDOS_SMTP_PASSWORD', help_text='ENV VAR NAME holding the password — value never in DB.', max_length=128)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('otp_option', models.CharField(choices=[('email', 'email'), ('whatsapp', 'whatsapp')], default='email', max_length=16)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, default='', max_length=64)),
                ('whatsapp_access_token', models.TextField(blank=True, default='', help_text='Prefer whatsapp_access_token_env_var in FundOS (Doc 6 §1).')),
                ('whatsapp_access_token_env_var', models.CharField(blank=True, default='FUNDOS_WHATSAPP_TOKEN', max_length=128)),
                ('whatsapp_otp_template_name', models.CharField(blank=True, default='', max_length=128)),
                ('whatsapp_alert_template_name', models.CharField(blank=True, default='alert_generic', max_length=128)),
                ('whatsapp_alert_image_template_name', models.CharField(blank=True, default='alert_generic_image', max_length=128)),
                ('whatsapp_otp_template_lang', models.CharField(blank=True, default='en', max_length=8)),
                ('ai_mocked', models.BooleanField(default=True, help_text='Global mock switch for all LLM roles.')),
                ('ai_guidance_data', models.TextField(blank=True, default='')),
                ('ai_guidance_documents', models.TextField(blank=True, default='')),
                ('ai_synthetic_disclosure_enabled', models.BooleanField(default=True, help_text='Forces "AI Generated Insights" labelling on.')),
                ('show_numeric_readiness', models.BooleanField(default=False)),
                ('enable_research_extensions', models.BooleanField(default=False)),
                ('enable_instrument_selection', models.BooleanField(default=True)),
                ('enable_dilution_simulator', models.BooleanField(default=True)),
                ('scoring_config_active_version', models.IntegerField(blank=True, null=True)),
                ('hard_gate_config_version', models.IntegerField(blank=True, null=True)),
                ('sector_taxonomy_map_version', models.IntegerField(blank=True, null=True)),
                ('investor_category_map_version', models.IntegerField(blank=True, null=True)),
                ('mandatory_ckb_fields', models.JSONField(blank=True, default=list, help_text='Field keys counted for Stage-1 completeness (BR-M1-000).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'db_table': 'app_configuration',
            },
        ),
        migrations.CreateModel(
            name='HardGateConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_no', models.SmallIntegerField()),
                ('precondition_key', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('version_no', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'hard_gate_config',
            },
        ),
        migrations.CreateModel(
            name='ResearchSourceFlags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('legal_cleared', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'research_source_flags',
            },
        ),
        migrations.CreateModel(
            name='SectorTaxonomyMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('founder_sector', models.CharField(max_length=128, unique=True)),
                ('canonical_sector', models.CharField(max_length=128)),
                ('canonical_subsector', models.CharField(blank=True, default='', max_length=128)),
                ('adjacent_sectors', models.JSONField(blank=True, default=list)),
                ('version_no', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'sector_taxonomy_map',
            },
        ),
        migrations.CreateModel(
            name='StageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_no', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('soft_dependencies', models.JSONField(blank=True, default=list)),
                ('estimated_duration_days', models.IntegerField(default=0)),
                ('optional_flags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'stage_config',
            },
        ),
        migrations.CreateModel(
            name='MasterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table', models.CharField(db_index=True, max_length=48)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('version_no', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'master_value',
                'unique_together': {('table', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InvestorCategoryMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(max_length=32)),
                ('raise_band', models.CharField(max_length=32)),
                ('band_low_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('band_high_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('primary', models.JSONField(default=list)),
                ('secondary', models.JSONField(default=list)),
                ('optional', models.JSONField(default=list)),
                ('version_no', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'm_investor_category_map',
                'unique_together': {('round_type', 'raise_band')},
            },
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scoring_config',
                'unique_together': {('version_no',)},
            },
        ),
    ]
