# Generated by Django 5.1.15 on 2026-09-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundosconfig", "0003_research_concurrency_5"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appconfiguration",
            name="profile_ocr_engine",
        ),
        migrations.RemoveField(
            model_name="appconfiguration",
            name="profile_ocr_page_limit",
        ),
        migrations.AlterField(
            model_name="appconfiguration",
            name="profile_ocr_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Read scanned pages and the text inside deck images by sending the FILE to a document-capable model, in place of a local OCR engine. Safe to leave on: a file the model cannot read still keeps whatever native extraction recovered, and the dossier records why. Turn off to skip the token cost, at the price of anything that exists only as pixels.",
                verbose_name="Read documents with a model",
            ),
        ),
    ]
