# Generated by Django 4.2.11 on 2026-07-06 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alertdefinition_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_deal_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='queued', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('artifact_id', models.UUIDField(blank=True, null=True)),
                ('requested_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generation_job',
                'indexes': [models.Index(fields=['deal_id', 'kind', '-created_at'], name='generation__deal_id_cbc41b_idx')],
            },
        ),
    ]
