# Generated by Django 4.2.11 on 2026-07-06 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable id (OPENAI/ANTHROPIC/GEMINI/LOCALGPU). Never change once in use — cost rows reference it.', max_length=32, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('provider_kind', models.CharField(choices=[('openai_chat', 'OpenAI Chat'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('deepinfra', 'DeepInfra (OpenAI-compatible)'), ('custom_rest', 'Custom REST')], max_length=32)),
                ('base_url', models.CharField(blank=True, default='', help_text='Inference server base, no trailing slash.', max_length=512)),
                ('default_model', models.CharField(blank=True, default='', max_length=128)),
                ('path_template', models.CharField(blank=True, default='', help_text='For custom_rest: e.g. /generate/{model}/', max_length=255)),
                ('api_key_env_var', models.CharField(blank=True, default='', help_text='NAME of the env var holding the key — value stays in secrets.', max_length=128)),
                ('timeout_seconds', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower = preferred.')),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_endpoint',
            },
        ),
        migrations.CreateModel(
            name='LLMRoleBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('research_synthesis', 'research_synthesis'), ('material_critique', 'material_critique'), ('readiness_summary', 'readiness_summary'), ('peer_insight', 'peer_insight'), ('raise_narrative', 'raise_narrative'), ('valuation_negotiation', 'valuation_negotiation'), ('instrument_explainer', 'instrument_explainer'), ('strategy_blueprint', 'strategy_blueprint'), ('investment_story', 'investment_story'), ('teaser', 'teaser'), ('pitch_story', 'pitch_story'), ('pitch_slides', 'pitch_slides'), ('fin_model_assist', 'fin_model_assist'), ('fin_review', 'fin_review'), ('im_section', 'im_section'), ('im_narrative', 'im_narrative'), ('im_consistency', 'im_consistency'), ('package_review', 'package_review'), ('objection_sim', 'objection_sim')], max_length=48, unique=True)),
                ('is_mocked', models.BooleanField(default=False)),
                ('max_output_tokens', models.IntegerField(default=2048)),
                ('temperature', models.FloatField(blank=True, help_text='Deterministic paths pass 0; leave empty for provider default.', null=True)),
                ('fallback_endpoint', models.ForeignKey(blank=True, db_column='fallback_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_roles', to='llm.llmendpoint', to_field='code')),
                ('primary_endpoint', models.ForeignKey(db_column='endpoint_code', on_delete=django.db.models.deletion.PROTECT, related_name='primary_roles', to='llm.llmendpoint', to_field='code')),
            ],
            options={
                'db_table': 'llm_role_binding',
            },
        ),
        migrations.CreateModel(
            name='LLMModelCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('input_cost_per_1k_inr', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_cost_per_1k_inr', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_model_cost',
                'unique_together': {('provider', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('function_name', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('calling_context', models.CharField(blank=True, default='', max_length=128)),
                ('deal_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_user_initiated', models.BooleanField(default=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, default='success', help_text='success | fallback | error | mocked', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('cost_inr', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('req_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_call_log',
            },
        ),
    ]
