# Generated by Django 4.2.11 on 2026-07-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmrolebinding',
            name='role',
            field=models.CharField(choices=[('research_synthesis', 'research_synthesis'), ('material_critique', 'material_critique'), ('readiness_summary', 'readiness_summary'), ('peer_insight', 'peer_insight'), ('raise_narrative', 'raise_narrative'), ('valuation_negotiation', 'valuation_negotiation'), ('instrument_explainer', 'instrument_explainer'), ('strategy_blueprint', 'strategy_blueprint'), ('investment_story', 'investment_story'), ('teaser', 'teaser'), ('pitch_story', 'pitch_story'), ('pitch_slides', 'pitch_slides'), ('fin_model_assist', 'fin_model_assist'), ('fin_review', 'fin_review'), ('im_section', 'im_section'), ('im_narrative', 'im_narrative'), ('im_consistency', 'im_consistency'), ('package_review', 'package_review'), ('objection_sim', 'objection_sim'), ('company_profile_section', 'company_profile_section'), ('company_profile_records', 'company_profile_records'), ('company_profile_field', 'company_profile_field'), ('founder_profile', 'founder_profile')], max_length=48, unique=True),
        ),
    ]
