# Generated by Django 4.2.11 on 2026-08-02 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_llmrolebinding_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModelCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google (Gemini)'), ('openai', 'OpenAI')], db_index=True, max_length=16)),
                ('model_string', models.CharField(help_text='Exact API model string, e.g. gemini-2.5-flash, claude-sonnet-4-6, gpt-4o.', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to retire/hide a model from selection without deleting configs that reference it.')),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_model_catalog',
                'ordering': ('provider', 'model_string'),
                'unique_together': {('provider', 'model_string')},
            },
        ),
        migrations.CreateModel(
            name='LLMConfigProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable id a feature references, e.g. cp_extract.basic_info or cp_structure.claude.', max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google (Gemini)'), ('openai', 'OpenAI')], max_length=16)),
                ('model_string', models.CharField(help_text='Chosen from the model catalog for this provider.', max_length=128)),
                ('system_instructions', models.TextField(blank=True, default='')),
                ('web_search', models.BooleanField(default=False, help_text='Live web search (Claude Web Search / Gemini Search grounding / OpenAI Web Search).')),
                ('web_fetch', models.BooleanField(default=False, help_text='Fetch a specific URL (Claude Web Fetch / Gemini URL context).')),
                ('maps_grounding', models.BooleanField(default=False, help_text='Gemini only — Maps grounding.')),
                ('function_calling', models.BooleanField(default=False)),
                ('code_execution', models.BooleanField(default=False)),
                ('max_uses', models.IntegerField(blank=True, help_text='Claude — cap searches per request. Blank = provider default.', null=True)),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Claude — restrict search to these domains. Mutually exclusive with blocked_domains.')),
                ('blocked_domains', models.JSONField(blank=True, default=list, help_text='Claude — exclude these domains. Mutually exclusive with allowed_domains.')),
                ('user_location', models.JSONField(blank=True, default=dict, help_text="Claude — localize search results (e.g. {'country':'IN'}).")),
                ('dynamic_filter', models.BooleanField(default=False, help_text='Claude — code-filter search results before context (requires code execution).')),
                ('structured_output', models.BooleanField(default=False)),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema the response must conform to when structured output is on.')),
                ('thinking_mode', models.CharField(choices=[('none', 'Off'), ('tokens', 'Token budget (Anthropic extended thinking)'), ('effort', 'Effort level (OpenAI reasoning)')], default='none', max_length=8)),
                ('thinking_budget', models.CharField(blank=True, default='', help_text='Token count (Anthropic) or effort level low|medium|high (OpenAI).', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(db_column='endpoint_code', help_text='Connection (base_url + API key) this profile runs on.', on_delete=django.db.models.deletion.PROTECT, related_name='config_profiles', to='llm.llmendpoint', to_field='code')),
            ],
            options={
                'db_table': 'llm_config_profile',
                'ordering': ('code',),
            },
        ),
    ]
