# Generated by Django 4.2.11 on 2026-08-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_cost_optimisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfigprofile',
            name='tier',
            field=models.CharField(choices=[('simple', 'Simple — extract from supplied text (no tools)'), ('advanced', 'Advanced / Web — retrieve from the internet (web search on)'), ('judgment', 'Judgement — reason over already-extracted data (no tools)')], db_index=True, default='simple', help_text='Which kind of work this model serves. Simple (simple): Pull structured values out of text the system already holds — website extract, uploaded documents, founder input. Tools: None. Cannot browse. Use when: The answer is present in the supplied context and the task is finding and shaping it.  |  Advanced / Web (advanced): Discover facts that are NOT in the supplied context by searching the public internet, then structure them. Tools: Web search (and URL fetch where the provider supports it). Use when: The task needs information nobody uploaded — filings, news, competitor data, regulatory changes.  |  Judgement (judgment): Reason over data another call already extracted: adjudicate conflicting figures, flag outliers, assess risk, write a thesis anchored in the data. Tools: None. Deliberately cannot browse — it must reason from the extraction, not go looking for new facts. Use when: The inputs are already structured and the value comes from interpretation rather than retrieval.', max_length=16),
        ),
        migrations.AlterField(
            model_name='tenantllmtier',
            name='config_profile',
            field=models.ForeignKey(db_column='config_profile_code', help_text='The model + capabilities used for this tenant/tier.', on_delete=django.db.models.deletion.PROTECT, related_name='tenant_tiers', to='llm.llmconfigprofile', to_field='code'),
        ),
        migrations.AlterField(
            model_name='tenantllmtier',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='NULL = global default for all tenants.', null=True),
        ),
        migrations.AlterField(
            model_name='tenantllmtier',
            name='tier',
            field=models.CharField(choices=[('simple', 'Simple — extract from supplied text (no tools)'), ('advanced', 'Advanced / Web — retrieve from the internet (web search on)'), ('judgment', 'Judgement — reason over already-extracted data (no tools)')], max_length=16),
        ),
    ]
