# Generated by Django 4.2.11 on 2026-08-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_judgment_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='search_count',
            field=models.IntegerField(default=-1, help_text='Searches performed in this call. -1 = unknown/not reported by the provider.'),
        ),
    ]
