# Generated by Django 4.2.11 on 2026-08-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_search_containment'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='config_profile',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Which LLMConfigProfile served the call. Without this you cannot attribute a quality change to a model change.', max_length=64),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='context_chars',
            field=models.IntegerField(default=0, help_text='Size of the context block sent. Correlates input volume with output quality — the key input to context tuning.'),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='output_signals',
            field=models.JSONField(blank=True, default=dict, help_text='Quality signals parsed from the response: needsInput, counts of missing/conflicts/records. These, not cost, are what tell you whether a prompt or model change helped.'),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='prompt_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Short hash of the system prompt actually sent. Changes when an admin edits the prompt, so results can be compared BEFORE and AFTER a prompt edit.', max_length=16),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='tier',
            field=models.CharField(blank=True, db_index=True, default='', help_text='simple / advanced / judgment as resolved for this call.', max_length=16),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='was_normalized',
            field=models.BooleanField(default=False, help_text='The response came back under unexpected keys and had to be remapped. Rising rates signal prompt/model drift.'),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='was_repaired',
            field=models.BooleanField(default=False, help_text='A second call was needed because JSON did not parse. A cheap model with a high repair rate is not cheap.'),
        ),
    ]
