# Generated by Django 4.2.11 on 2026-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0012_assessment_inputs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfigprofile',
            name='max_uses',
            field=models.IntegerField(blank=True, help_text="Cap searches per request. Blank uses the deployment default (6) — it never means 'unlimited' and never means 'no directive'.", null=True),
        ),
    ]

# Shipped in v27.5. The model change landed in v27.3 without its migration
# file, so `manage.py migrate` reported unapplied changes on deployment and
# the file had to be generated on the server. Generating migrations on a
# production host is how two environments end up with different schemas and
# no record of which is right.
