# Generated by Django 4.2.11 on 2026-08-20 14:32

"""Company Master Data Pipeline roles, bindable in the admin.

`LLM_ROLES` is the choice list for LLMRoleBinding, so a role absent from it
cannot be bound — and `llm_generate` raises LLMUnavailable when a role has no
binding. Without this migration both pipeline roles would fail at runtime on
any system with mocked AI switched off, with no way for an administrator to
fix it from the console. That is the exact defect migration 0010 was written
to correct for seven other roles; this keeps the list honest.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0013_alter_llmconfigprofile_max_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmrolebinding',
            name='role',
            field=models.CharField(choices=[('research_synthesis', 'research_synthesis'), ('material_critique', 'material_critique'), ('readiness_summary', 'readiness_summary'), ('peer_insight', 'peer_insight'), ('raise_narrative', 'raise_narrative'), ('valuation_negotiation', 'valuation_negotiation'), ('valuation_explainer', 'valuation_explainer'), ('instrument_explainer', 'instrument_explainer'), ('strategy_blueprint', 'strategy_blueprint'), ('investment_story', 'investment_story'), ('teaser', 'teaser'), ('pitch_story', 'pitch_story'), ('pitch_slides', 'pitch_slides'), ('fin_model_assist', 'fin_model_assist'), ('fin_review', 'fin_review'), ('im_section', 'im_section'), ('im_narrative', 'im_narrative'), ('im_consistency', 'im_consistency'), ('package_review', 'package_review'), ('objection_sim', 'objection_sim'), ('company_profile_section', 'company_profile_section'), ('company_profile_records', 'company_profile_records'), ('company_profile_structured', 'company_profile_structured'), ('company_profile_field', 'company_profile_field'), ('founder_profile', 'founder_profile'), ('company_profile_deep_extract', 'company_profile_deep_extract'), ('profile_qa', 'profile_qa'), ('profile_research_batch', 'profile_research_batch'), ('profile_synthesis', 'profile_synthesis'), ('company_profile_judgment', 'company_profile_judgment'), ('assessment_extraction', 'assessment_extraction'), ('assessment_rubric_review', 'assessment_rubric_review'), ('assessment_inputs', 'assessment_inputs'), ('investor_classification', 'investor_classification'), ('investor_identity', 'investor_identity')], max_length=48, unique=True),
        ),
    ]
