# Generated by Django 5.1.15 on 2026-09-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0014_pipeline_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmrolebinding",
            name="role",
            field=models.CharField(
                choices=[
                    ("research_synthesis", "research_synthesis"),
                    ("material_critique", "material_critique"),
                    ("readiness_summary", "readiness_summary"),
                    ("peer_insight", "peer_insight"),
                    ("raise_narrative", "raise_narrative"),
                    ("valuation_negotiation", "valuation_negotiation"),
                    ("valuation_explainer", "valuation_explainer"),
                    ("instrument_explainer", "instrument_explainer"),
                    ("strategy_blueprint", "strategy_blueprint"),
                    ("investment_story", "investment_story"),
                    ("teaser", "teaser"),
                    ("pitch_story", "pitch_story"),
                    ("pitch_slides", "pitch_slides"),
                    ("fin_model_assist", "fin_model_assist"),
                    ("fin_review", "fin_review"),
                    ("im_section", "im_section"),
                    ("im_narrative", "im_narrative"),
                    ("im_consistency", "im_consistency"),
                    ("package_review", "package_review"),
                    ("objection_sim", "objection_sim"),
                    ("company_profile_section", "company_profile_section"),
                    ("company_profile_records", "company_profile_records"),
                    ("company_profile_structured", "company_profile_structured"),
                    ("company_profile_field", "company_profile_field"),
                    ("founder_profile", "founder_profile"),
                    ("company_profile_deep_extract", "company_profile_deep_extract"),
                    ("profile_qa", "profile_qa"),
                    ("profile_research_batch", "profile_research_batch"),
                    ("profile_synthesis", "profile_synthesis"),
                    ("company_profile_judgment", "company_profile_judgment"),
                    ("assessment_extraction", "assessment_extraction"),
                    ("assessment_rubric_review", "assessment_rubric_review"),
                    ("assessment_inputs", "assessment_inputs"),
                    ("investor_classification", "investor_classification"),
                    ("investor_identity", "investor_identity"),
                    ("document_read", "document_read"),
                ],
                max_length=48,
                unique=True,
            ),
        ),
    ]
