# Generated by Django 4.2.11 on 2026-07-06 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('document_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('investment_material', 'investment_material'), ('financial', 'financial'), ('legal', 'legal'), ('company', 'company'), ('other', 'other')], default='other', max_length=32)),
                ('detected_type', models.CharField(blank=True, default='', max_length=48)),
                ('ai_status', models.CharField(blank=True, choices=[('', ''), ('reuse', 'reuse'), ('improve', 'improve'), ('replace', 'replace'), ('generate', 'generate')], default='', max_length=12)),
                ('scan_status', models.CharField(choices=[('pending', 'pending'), ('clean', 'clean'), ('infected', 'infected')], default='pending', max_length=12)),
                ('summary', models.TextField(blank=True, default='')),
                ('extracted_metrics', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='[{target_section, issue, suggested_change, effort_min}] (BR-M1-021)')),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('ocr_applied', models.BooleanField(default=False)),
                ('extraction_status', models.CharField(choices=[('pending', 'pending'), ('extracted', 'extracted'), ('failed', 'failed')], default='pending', max_length=12)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_asset',
            },
        ),
        migrations.CreateModel(
            name='ReadinessAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('version_no', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_band', models.CharField(blank=True, default='', max_length=24)),
                ('summary', models.TextField(blank=True, default='')),
                ('scoring_config_version_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('current', 'current'), ('pending_recalc', 'pending_recalc')], default='current', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'readiness_assessment',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('filename', models.CharField(max_length=255)),
                ('declared_size', models.BigIntegerField()),
                ('mime', models.CharField(blank=True, default='', max_length=128)),
                ('category', models.CharField(default='other', max_length=32)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('chunk_size', models.IntegerField(default=8388608)),
                ('chunks_received', models.IntegerField(default=0)),
                ('received_chunk_numbers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'open'), ('assembling', 'assembling'), ('scanning', 'scanning'), ('complete', 'complete'), ('failed', 'failed'), ('aborted', 'aborted')], default='open', max_length=12)),
                ('storage_tmp_uri', models.CharField(blank=True, default='', max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='readiness.materialasset')),
            ],
            options={
                'db_table': 'upload_session',
            },
        ),
        migrations.CreateModel(
            name='ReadinessGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('strength', 'strength'), ('risk', 'risk'), ('missing', 'missing'), ('recommendation', 'recommendation')], max_length=16)),
                ('dimension', models.CharField(blank=True, default='', max_length=48)),
                ('text', models.TextField()),
                ('impact', models.CharField(blank=True, default='', max_length=8)),
                ('founder_action', models.CharField(choices=[('none', 'none'), ('accepted', 'accepted'), ('acknowledged', 'acknowledged'), ('deferred', 'deferred')], default='none', max_length=16)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='readiness.readinessassessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'readiness_gap',
            },
        ),
        migrations.CreateModel(
            name='MaterialExtractionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('ckb_field_id', models.UUIDField(blank=True, null=True)),
                ('extracted_value_json', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_links', to='readiness.materialasset')),
            ],
            options={
                'db_table': 'material_extraction_link',
            },
        ),
        migrations.CreateModel(
            name='ReadinessDimension',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('dimension', models.CharField(max_length=48)),
                ('status', models.CharField(max_length=20)),
                ('sub_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='readiness.readinessassessment')),
            ],
            options={
                'db_table': 'readiness_dimension',
                'indexes': [models.Index(fields=['assessment'], name='readiness_d_assessm_688be9_idx')],
            },
        ),
    ]
