# Generated by Django 5.1.15 on 2026-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readiness", "0002_extraction_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialasset",
            name="inconsistencies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Contradictions the model found INSIDE this document — a figure stated two ways, a date that disagrees with a chart. Strings, in the model's own words.",
            ),
        ),
        migrations.AddField(
            model_name="materialasset",
            name="missing_information",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="What a reader of this document would expect and not find. Distinct from a low section-coverage count: this is the model's reading, not a checklist match.",
            ),
        ),
    ]
