"""Fan the synthesized profile out into storage, one section at a time.

The synthesis call returns one normalized document; the database keeps it as a
``ProfileSection`` row per section plus five record tables. This module is the
bridge, and it is deliberately thin: the actual coercion, validation and
storage-key resolution already exist in
:func:`fundos.profile.section_writer.update_section_from_data`, which is the
same function that serves a human PATCH. Using it for both is what keeps the
two write paths from drifting — a field the API can save is a field generation
can populate, by construction.

Isolation policy
----------------
Each section is written in its own transaction and its own try/except. One
section failing — a malformed row, a value too long for its column — must cost
that section and nothing else. The alternative was demonstrated by the previous
pipeline: a failed ``INSERT`` aborted the surrounding transaction and every
later query died with "you can't execute queries until the end of the 'atomic'
block", which surfaced as an unrelated later step failing and being blamed.
"""
import logging

from django.db import transaction

from fundos.profile import schema

logger = logging.getLogger("fundos.profile")

# Sections whose storage is owned by something other than the section writer.
#
# document_center reflects the ProfileDocument table, which the upload path
# maintains and `recompute_structured_sections` reconciles; there is nothing
# for a generation run to write into it.
NOT_WRITABLE = {"document_center"}


def write_profile(profile, generated, *, user=None, model_version=""):
    """Persist a normalized profile. Never raises.

    :param generated: The output of
        :func:`fundos.profile.schema.normalize_profile` — every section key
        present, every ``data`` matching its declared container.
    :returns: ``{"written": [...], "empty": [...], "failed": [...]}`` — which
        sections landed, which the model left empty, and which could not be
        stored and why. The caller records all three on the run: a section that
        is always empty is a pipeline bug, one that varies with sources is
        working correctly, and one that always *fails* is neither.
    """
    sections = (generated or {}).get("sections") or {}
    written, empty, failed = [], [], []

    for key in schema.section_keys():
        if key in NOT_WRITABLE:
            continue
        block = sections.get(key) or {}
        data = block.get("data")
        sources = block.get("sources") or {}

        if not schema.is_populated(data):
            # Not a failure. The model looked and found nothing, which is the
            # correct outcome for a company with no funding history — and is
            # exactly the distinction `is_populated` exists to preserve.
            empty.append(key)
            continue

        try:
            with transaction.atomic():
                _write_one(profile, key, data, sources, user=user,
                           model_version=model_version)
            written.append(key)
        except Exception as exc:
            logger.warning("PIPELINE: could not write section %s: %s",
                           key, exc)
            failed.append({"section": key,
                           "error": f"{type(exc).__name__}: {exc}"})
            _mark_needs_input(profile, key)

    return {"written": written, "empty": empty, "failed": failed}


def _write_one(profile, key, data, sources, *, user, model_version):
    from fundos.profile.section_writer import update_section_from_data

    row = update_section_from_data(
        profile, key, data, user=user, by_ai=True,
        ai_model_version=model_version,
        change_summary="Generated by the company profile pipeline")
    _store_sources(profile, key, row, data, sources)


#: The field that identifies a row to a reader, in the order we look for it.
#: A citation is matched back to its item by this rather than by position,
#: because position survives only until something reorders the list.
_IDENTIFYING_FIELDS = ("name", "title", "metric", "market", "stream", "round",
                       "filename")


def _identity(item):
    """The value that names this item, lowercased, or "" if it has none."""
    if not isinstance(item, dict):
        return ""
    for field in _IDENTIFYING_FIELDS:
        value = item.get(field)
        if isinstance(value, str) and value.strip():
            return value.strip().casefold()
    return ""


def _store_sources(profile, key, row, data, sources):
    """Key each citation the way a confirmation is keyed, then store it.

    The model cites an array item by POSITION, because position is all it can
    see. Position is the one thing that cannot be stored: insert a founder at
    the top on the next run and every citation below it now describes somebody
    else. So it is resolved here, once, at the only moment both the model's
    list and the stored items are in hand.

    Resolution goes through the SERIALIZER, not through `structured`, because
    a section's rows live in one of three places and only one of them is
    `structured`: an object section keeps fields there, a JSON list keeps rows
    under `items`, and founders, competitors, funding rounds and news live in
    their own tables and leave `structured` empty. Reading `structured`
    directly got two of those three right — entity-backed sections stored raw
    positions like "0", which address nothing at all.

    Matching is by the item's NAME rather than its index, because the rows
    come back from the database in no guaranteed order; lining them up by
    position would attach a citation to whichever founder happened to be
    returned third. A citation that cannot be matched is dropped: an
    unattributed value is a gap, an misattributed one is a lie.
    """
    from fundos.profile.models import ProfileSection
    from fundos.profile.schema import storage_key_for
    from fundos.profile.spec_serializer import serialize_section

    if not sources:
        return
    internal = storage_key_for(key)
    section = ProfileSection.objects.filter(
        profile=profile, section_key=internal, is_active=True).first()
    if section is None:
        # A pure entity list — founders, competitors — has no narrative row,
        # because its content lives in its own table. The row is still where
        # this section's ANNOTATIONS live: its citations and its
        # confirmations. Returning here is why founders came back
        # `cited: false` while thirteen other sections cited fine.
        section = ProfileSection.objects.create(
            profile=profile, section_key=internal,
            tenant_id=profile.tenant_id, is_active=True)

    if not isinstance(data, list):
        # Object section: the model keys by field name, which is already the
        # address a confirmation uses.
        section.field_sources = dict(sources)
        section.save(update_fields=["field_sources", "updated_at"])
        return

    try:
        served = serialize_section(profile, key).get("data") or []
    except Exception:                       # pragma: no cover - never fatal
        served = []
    if not isinstance(served, list):
        return

    by_identity = {}
    for item in served:
        name = _identity(item)
        if name and isinstance(item, dict) and item.get("id"):
            by_identity.setdefault(name, str(item["id"]))

    resolved = {}
    for field, citation in sources.items():
        # A second or third source for one item arrives as "0.1", "0.2" --
        # the item's position, then which extra it is. It is stored under the
        # item's id with the same suffix ("<id>.1"), which is where the field
        # sources endpoint collects extras. `int("0.2")` fails, and every
        # extra source for a founder or competitor was silently discarded.
        base, dot, extra = str(field).rpartition(".")
        suffix = ""
        if dot and extra.isdigit() and (
                base.strip().isdigit()
                or base.strip().casefold() in by_identity):
            # Only when what precedes the dot is itself an address, so a
            # name like "Company 2.0" is not mistaken for an extra.
            suffix, field = f".{extra}", base
        try:
            cited = data[int(field)]
        except (ValueError, TypeError, IndexError):
            # Not a position. A model that has just written a list of people
            # will as readily key their citations by name as by index, and
            # a name is the better address of the two -- it is what the
            # matching below reduces the position to anyway.
            item_id = by_identity.get(str(field).strip().casefold())
            if item_id:
                resolved[item_id + suffix] = citation
            continue
        item_id = by_identity.get(_identity(cited))
        if not item_id and len(served) == len(data):
            # No name to match on, but the two lists are the same length, so
            # position is the best available answer and is at least internally
            # consistent.
            candidate = served[int(field)]
            item_id = (str(candidate.get("id"))
                       if isinstance(candidate, dict) and candidate.get("id")
                       else "")
        if item_id:
            resolved[item_id + suffix] = citation

    if resolved:
        section.field_sources = resolved
        section.save(update_fields=["field_sources", "updated_at"])


def _mark_needs_input(profile, wire_key):
    """Flag a section the run could not populate, so the founder is asked.

    Best-effort: this runs in the failure path, and a failure to record a
    failure must not escalate.
    """
    from fundos.profile.models import ProfileSection

    try:
        storage_key = schema.storage_key_for(wire_key)
        ProfileSection.objects.filter(
            profile=profile, section_key=storage_key, is_active=True
        ).update(needs_input=True)
    except Exception:
        logger.debug("could not flag %s as needing input", wire_key,
                     exc_info=True)
