# Generated by Django 4.2.11 on 2026-07-23 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_user_last_active_deal_id_generationjob'),
        ('companyprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTargets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_id', models.UUIDField(db_index=True)),
                ('target_raise_value', models.DecimalField(blank=True, decimal_places=2, help_text='How much the company intends to raise.', max_digits=20, null=True)),
                ('target_raise_ccy', models.CharField(default='USD', max_length=3)),
                ('target_raise_basis', models.CharField(default='target', max_length=32)),
                ('pre_money_value', models.DecimalField(blank=True, decimal_places=2, help_text='Company valuation before the new money comes in.', max_digits=20, null=True)),
                ('pre_money_ccy', models.CharField(default='USD', max_length=3)),
                ('pre_money_basis', models.CharField(default='pre_money', max_length=32)),
                ('post_money_value', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated: pre-money + target raise. Never entered.', max_digits=20, null=True)),
                ('post_money_ccy', models.CharField(default='USD', max_length=3)),
                ('post_money_basis', models.CharField(default='post_money', max_length=32)),
                ('dilution_pct', models.DecimalField(blank=True, decimal_places=3, help_text='Calculated: raise / post-money x 100. Never entered.', max_digits=6, null=True)),
                ('target_raise_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pre_money_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('post_money_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fx_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('fx_as_of', models.DateField(blank=True, null=True)),
                ('fx_source', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(default='founder', help_text='founder | advisor | derived_from_strategy', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_targets', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deal_targets',
            },
        ),
        migrations.AddConstraint(
            model_name='dealtargets',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('deal_id',), name='uq_active_deal_targets'),
        ),
    ]
