# Generated by Django 4.2.11 on 2026-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0002_dealtargets_dealtargets_uq_active_deal_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='fy_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='investors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='competitor',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
