# Generated by Django 4.2.11 on 2026-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0003_competitor_fy_year_competitor_investors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
