# Generated by Django 4.2.11 on 2026-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0006_source_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='judgment',
            field=models.JSONField(blank=True, default=dict, help_text='Distilled output of the Judgement-tier call. Reused as authoritative context by cheaper calls.'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='holder_category',
            field=models.CharField(blank=True, default='Investor', help_text='Founder | Investor | ESOP | Other — drives the cap-table split.', max_length=16),
        ),
        migrations.AlterField(
            model_name='investor',
            name='rounds',
            field=models.JSONField(blank=True, default=list, help_text='Round names this investor participated in.'),
        ),
    ]
