# Generated by Django 4.2.11 on 2026-08-04 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyprofile', '0007_judgment_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('mode', models.CharField(blank=True, default='', help_text='consolidated / per_section / skipped', max_length=24)),
                ('forced', models.BooleanField(default=False)),
                ('sources_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_stats', models.JSONField(blank=True, default=dict, help_text="Per-source presence and size, e.g. {'website_chars': 4200, 'document_count': 3, 'document_chars': 8100, 'research_keys': ['market'], 'founder_count': 2}. The denominator for every quality question about this run.")),
                ('source_failures', models.JSONField(blank=True, default=list, help_text='Adapters that failed. A silently failing source looks exactly like a company with no public data.')),
                ('sections_generated', models.JSONField(blank=True, default=list)),
                ('sections_skipped', models.JSONField(blank=True, default=list)),
                ('sections_needing_input', models.JSONField(blank=True, default=list, help_text='Sections still incomplete after the run. Track these across runs: one that is ALWAYS empty is a bug, one that varies with sources is working correctly.')),
                ('completeness_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('judgment_ran', models.BooleanField(default=False)),
                ('conflicts_found', models.IntegerField(default=0, help_text='Conflicts the extraction stage surfaced. Zero on a company with messy public data usually means the model silently picked — a quality FAILURE that looks like success.')),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('llm_calls', models.IntegerField(default=0)),
                ('total_cost_inr', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('total_search_count', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='companyprofile.companyprofile')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_generation_run',
                'indexes': [models.Index(fields=['profile', '-created_at'], name='profile_gen_profile_b15c69_idx'), models.Index(fields=['tenant_id', '-created_at'], name='profile_gen_tenant__795265_idx')],
            },
        ),
    ]
