# Generated by Django 4.2.11 on 2026-08-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0008_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fundinground',
            name='lead_investors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
