# Generated by Django 4.2.11 on 2026-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0009_api_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
