# Generated by Django 4.2.11 on 2026-08-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0010_company_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinground',
            name='date_precision',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('day', 'Exact date'), ('month', 'Month'), ('year', 'Year')], default='', max_length=5),
        ),
    ]
