# Generated by Django 4.2.11 on 2026-08-11 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyprofile', '0011_fundinground_date_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAssessmentInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('input_key', models.CharField(db_index=True, help_text="The workbook's own parameter key, e.g. TEAM_COFDR_YRS. Not a FundOS name — matching the workbook exactly is what removes the translation layer between step 1 and step 2.", max_length=48)),
                ('value', models.CharField(blank=True, default='', help_text="The raw value as extracted. Kept as text because the engine parses it, and because 'about 40' is more honest than silently rounding to 40.", max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('source_type', models.CharField(choices=[('profile', 'Company profile research'), ('document', 'Uploaded document'), ('benchmark', 'Sector benchmark table'), ('founder', 'Founder-entered'), ('computed', 'Derived from other profile data')], default='profile', max_length=32)),
                ('source_url', models.CharField(blank=True, default='', help_text='Where this was found. Required in spirit: Evidence & Workings has to name a source per figure.', max_length=1024)),
                ('source_detail', models.TextField(blank=True, default='')),
                ('source_tier', models.IntegerField(blank=True, help_text='1 primary document, 2 company-owned, 3 reputable third party, 4 inferred. Decides which value wins when two sources disagree.', null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('is_founder_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_inputs', to='companyprofile.companyprofile')),
            ],
            options={
                'db_table': 'company_profile_assessment_input',
                'ordering': ('input_key',),
                'indexes': [models.Index(fields=['profile', 'input_key'], name='company_pro_profile_ce67db_idx')],
                'unique_together': {('profile', 'input_key')},
            },
        ),
    ]
