# Generated by Django 5.1.15 on 2026-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyprofile", "0014_confirmed_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilesection",
            name="field_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field provenance: {field_or_item_id: {source, locator, quote}}. Served by the field sources endpoint.",
            ),
        ),
        migrations.AlterField(
            model_name="profilesection",
            name="confirmed_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Field keys the founder has explicitly confirmed (AI Draft → Confirmed). Used by the readiness scorer.",
            ),
        ),
    ]
