# Generated by Django 5.1.15 on 2026-09-10 18:37

from django.db import migrations, models


def _label_existing_as_usd_millions(apps, schema_editor):
    """Every row written before this migration was USD millions by contract.

    `amount_usd_mn` was the only place an amount could go, so the scale was
    implicit in the column name and blank in the data. Left blank it renders
    as "US$ 2.4" — which reads as two dollars forty, not $2.4 million. The
    figures are not changed; only the label they always had is written down.
    """
    FundingRound = apps.get_model("companyprofile", "FundingRound")
    FundingRound.objects.filter(
        amount_denomination="").exclude(amount_value=None).update(
        amount_denomination="Mn")


def _unlabel(apps, schema_editor):
    FundingRound = apps.get_model("companyprofile", "FundingRound")
    FundingRound.objects.filter(amount_denomination="Mn").update(
        amount_denomination="")


class Migration(migrations.Migration):

    dependencies = [
        ("companyprofile", "0015_profilesection_field_sources_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundinground",
            name="amount_denomination",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Scale as written: Cr, L, K, Mn, Bn, or blank for whole units. Crore and lakh are kept because that is how the figure was reported, and converting at storage makes it unrecognisable to whoever wrote it.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="fundinground",
            name="amount_usd_mn",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="DERIVED from the three fields above for comparison and sorting. Never authoritative; blank when no rate applies.",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fundinground",
            name="fx_as_of",
            field=models.DateField(
                blank=True, help_text="When that rate was struck.", null=True
            ),
        ),
        migrations.AddField(
            model_name="fundinground",
            name="fx_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Units of amount_ccy per USD used for amount_usd_mn.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.RunPython(_label_existing_as_usd_millions, _unlabel),
    ]
